# Storage
version: "2"
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
      - MYSQL_HOME=/etc
    volumes:
      - ./.docker/etc/my.cnf:/etc/my.cnf
    hostname: dbhost
    expose:
      - "3306"

  php:
    image: kducharm/bowline-centos
    command: php-fpm
    environment:
      - COMPOSER_HOME=/.composer
      - HOST_USER=${HOST_UID}:${HOST_GID}
      - HOST_OS=${HOST_OS}
    expose:
      - "9000"
    links:
      - db:dbhost
    hostname: php_host

  web:
    image: kducharm/bowline-centos
    command: httpd -D FOREGROUND -e debug
    environment:
      - HOST_USER=${HOST_UID}:${HOST_GID}
      - HOST_OS=${HOST_OS}
    expose:
      - "80"
    links:
      - db:dbhost
      - php:php_host
    volumes_from:
      - php
    hostname: drupal

volumes:
  bowline_filesync:
    external:
      name: "${SLUG}_filesync"
