# Storage
version: "2"
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
      - MYSQL_HOME=/etc
    volumes:
      - ./.docker/etc/my.cnf:/etc/my.cnf
    hostname: dbhost
    expose:
      - "3306"

  web:
    image: kducharm/drupal-bowline
    command: apachectl -D FOREGROUND -e debug
    environment:
      - HOST_USER=${HOST_UID}:${HOST_GID}
      - HOST_OS=${HOST_OS}
    expose:
      - "80"
    links:
      - db:dbhost
    volumes:
      - bowline_filesync:/var/www:nocopy
    hostname: drupal

volumes:
  bowline_filesync:
    external:
      name: "${SLUG}_filesync"
